import {
    faHome,
    faChalkboardTeacher,
    faMicrophone,
    faStar,
    faLocationArrow,
    faBookOpen,
    faBookReader,
    faQuestion,
    faUser,
    faWrench,
    faSearch,
    faPlay,
    faBomb,
    faBookmark,
    faComment,
    faUserMd,
    faKey,
    faAngleRight,
    faLongArrowAltLeft
} from "@fortawesome/free-solid-svg-icons"

export {
    faLongArrowAltLeft,
    faAngleRight,
    faKey,
    faUserMd,
    faBookmark,
    faComment,
    faBomb,
    faPlay,
    faSearch,
    faWrench,
    faUser,
    faQuestion,
    faStar,
    faHome,
    faChalkboardTeacher,
    faMicrophone,
    faLocationArrow,
    faBookOpen,
    faBookReader
}
